apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coolstore-inventory-quarkus
  description: "Inventory microservice for Coolstore"
  annotations:
    #argocd/app-selector: rht-gitops.com/janus-argocd=coolstore-inventory-quarkus-bootstrap
    #backstage.io/kubernetes-id: coolstore-inventory-quarkus
    backstage.io/kubernetes-namespace: rhdh-demo
    #janus-idp.io/tekton: coolstore-inventory-quarkus
    backstage.io/source-location: url:https://github.com/manwendra-hotmail/techzone-demo.git
    backstage.io/techdocs-ref: url:https://github.com/manwendra-hotmail/techzone-demo.git
    #gitlab.com/project-slug: development/coolstore-inventory-quarkus
    quay.io/repository-slug: "quayadmin/coolstore-inventory-quarkus"
  tags:
    - java
    - quarkus
    - maven
    - demo
    - coolstore
  links:
    - url: https://console-openshift-console.apps.cluster-bjwf7.sandbox185.opentlc.com/dev-pipelines/ns/coolstore-dev/
      title: OpenShift Pipelines
      icon: web
    - url: https://devspaces.apps.cluster-bjwf7.sandbox185.opentlc.com/#https://gitlab-gitlab.apps.cluster-bjwf7.sandbox185.opentlc.com/development/coolstore-inventory-quarkus
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-bjwf7.sandbox185.opentlc.com/#https://gitlab-gitlab.apps.cluster-bjwf7.sandbox185.opentlc.com/development/coolstore-inventory-quarkus?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user1"
  system: coolstore-coolstore
  providesApis:
    - coolstore-inventory-quarkus-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: coolstore-coolstore
  tags:
    - coolstore
    - demo
spec:
  owner: "user1"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: coolstore-inventory-quarkus-api
  description: "Inventory microservice for Coolstore"
spec:
  type: openapi
  lifecycle: production
  owner: "user1"
  system: coolstore-coolstore
  definition:
    $text: ./openapi.yaml
