apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: inventory-trigger
spec:
  broker: default
  filter:
    attributes:
      type: wakeup
  subscriber:
    ref:
     apiVersion: v1
     kind: Service
     name: inventory
